let SecondMassiv = [
  {
    id: 9,
    vidios: "https://www.youtube.com/embed/B-brDBjI74M",
    rol: "shorts",
    subscribed: true,
    texts: "Konor McGregor",
    watchs: "157m view",
    type: "sport",
    all: "all",
  },
  {
    id: 10,
    vidios: "https://www.youtube.com/embed/yZqhBHPeuGc",
    rol: "shorts",
    subscribed: false,
    texts: "Bmw x5 G05",
    watchs: "3.200 view",
    type: "cars",
    all: "all",
  },
  {
    id: 11,
    vidios: "https://www.youtube.com/embed/QjMJsQx_O7o",
    rol: "shorts",
    subscribed: true,
    texts: "Sowt programing developer",
    watchs: "1.2m view",
    type: "programming",
    all: "all",
  },
  {
    id: 12,
    vidios: "https://www.youtube.com/embed/-lsOZHFCpIk",
    rol: "shorts",
    subscribed: true,
    texts: "Lubov i son ya naydu",
    watchs: "1.9m view",
    type: "music",
    all: "all",
  },
  {
    id: 13,
    vidios: "https://www.youtube.com/embed/dAgOgzEL8V4",
    rol: "shorts",
    subscribed: true,
    texts: "Shaxriyor vc Timati",
    watchs: "1.1m view",
    type: "interview",
    all: "all",
  },
  {
    id: 14,
    vidios: "https://www.youtube.com/embed/_FUosrF-fKQ",
    rol: "shorts",
    subscribed: true,
    texts: "Islam Itlyashev na svadbe",
    watchs: "1m view",
    type: "Music",
    all: "all",
  },
];
export default SecondMassiv;
